// vue/src/App.vue
<template>
    <div :style="styles.container">
        <Card header="State">
            <State />
        </Card>
        <Card header="Reactivity">
            <Reactivity />
        </Card>
        <Card header="Binding">
            <Binding />
        </Card>
        <Card header="Components">
            <ComponentsCounter />
        </Card>
        <Card header="Stores">
            <StoresCounter />
        </Card>
        <Card header="Conditionals">
            <Conditionals />
        </Card>
        <Card header="Loops">
            <Loops />
        </Card>
        <Card header="Css">
            <Css />
        </Card>
        <Card header="Slots">
            <Slots />
        </Card>
    </div>
</template>

<script setup>
import Card from "./Card.vue";
import State from "./examples/State.vue";
import Reactivity from "./examples/Reactivity.vue";
import Binding from "./examples/Binding.vue";
import ComponentsCounter from "./examples/ComponentsCounter.vue";
import StoresCounter from "./examples/StoresCounter.vue";
import Conditionals from "./examples/Conditionals.vue";
import Loops from "./examples/Loops.vue";
import Css from "./examples/Css.vue";
import Slots from "./examples/Slots.vue";

const styles = {
    container: {
        display: "flex",
        flexWrap: "wrap",
        gap: "20px",
        padding: "20px",
    },
};
</script>

// svelte-5/src/App.svelte
<script>
    import Card from "./Card.svelte";
    import State from "./examples/State.svelte";
    import Css from "./examples/Css.svelte";
    import Binding from "./examples/Binding.svelte";
    import ComponentsCounter from "./examples/ComponentsCounter.svelte";
    import Slots from "./examples/Slots.svelte";
    import StoresCounter from "./examples/StoresCounter.svelte";
    import Reactivity from "./examples/Reactivity.svelte";
    import Conditionals from "./examples/Conditionals.svelte";
    import Loops from "./examples/Loops.svelte";
</script>

<div class="container">
    <Card>
        <span slot="header">State</span>
        <State />
    </Card>

    <Card>
        <span slot="header">Reactivity</span>
        <Reactivity />
    </Card>

    <Card>
        <span slot="header">Binding</span>
        <Binding />
    </Card>

    <Card>
        <span slot="header">Components</span>
        <ComponentsCounter />
    </Card>

    <Card>
        <span slot="header">Stores</span>
        <StoresCounter />
    </Card>

    <Card>
        <span slot="header">Conditionals</span>
        <Conditionals />
    </Card>

    <Card>
        <span slot="header">Loops</span>
        <Loops />
    </Card>

    <Card>
        <span slot="header">CSS</span>
        <Css />
    </Card>

    <Card>
        <span slot="header">Slots</span>
        <Slots />
    </Card>
</div>

<style>
    .container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        padding: 20px;
    }
</style>
