// angular/src/app/examples/conditionals.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-conditionals',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button *ngIf="loggedIn(); else loggedOut" (click)="toggle()">Log out</button>
    <ng-template #loggedOut>
      <button (click)="toggle()">Log in</button>
    </ng-template>
  `,
})
export class ConditionalsComponent {
  loggedIn = signal(false);

  toggle() {
    this.loggedIn.update((v) => !v);
  }
}

// react/src/examples/Conditionals.jsx
import { useState } from "react";

export default function Conditionals() {
    const [loggedIn, setLoggedIn] = useState(false);

    function toggle() {
        setLoggedIn(!loggedIn);
    }

    return <>{loggedIn ? <button onClick={toggle}>Log out</button> : <button onClick={toggle}>Log in</button>}</>;
}
