// angular/src/app/examples/css.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-css',
  standalone: true,
  template: `
    <span style="color: orange; font-weight: bold;">Svelte</span>
    <span>&gt;</span>
    <span class="trash">React</span>
  `,
  styles: [
    `
      span {
        font-size: 40px;
      }

      .trash {
        color: blue;
        font-weight: bold;
      }
    `,
  ],
})
export class CssComponent {}

// react/src/examples/Css.jsx
export default function Css() {
    const styles = {
        span: {
            fontSize: "40px",
        },
        trash: {
            color: "blue",
            fontWeight: "bold",
        },
    };

    return (
        <>
            <span style={{ color: "orange", fontWeight: "bold", ...styles.span }}>Svelte</span>
            <span style={styles.span}>&gt;</span>
            <span style={{ ...styles.span, ...styles.trash }}>React</span>
        </>
    );
}
