// angular/src/app/examples/loops.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-loops',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="container">
      <div *ngFor="let todo of todos(); let i = index" class="todo">
        <span class="text">{{ i }} {{ todo.text }}</span>
      </div>
    </div>
  `,
})
export class LoopsComponent {
  todos = signal([
    { id: 1, text: 'foo' },
    { id: 2, text: 'bar' },
    { id: 3, text: 'baz' },
  ]);
}

// react/src/examples/Loops.jsx
import { useState } from "react";

export default function Loops() {
    const [todos] = useState([
        { id: 1, text: "foo" },
        { id: 2, text: "bar" },
        { id: 3, text: "baz" },
    ]);

    return (
        <>
            {todos.map((todo, i) => (
                <div key={todo.id} className="todo">
                    <span className="text">
                        {i} {todo.text}
                    </span>
                </div>
            ))}
        </>
    );
}
