// svelte-4/src/examples/Reactivity.svelte
<script>
    let randomNumber = "";

    function generateRandomNumber() {
        randomNumber = Math.round(Math.random() * 100);
    }

    $: isEven = randomNumber % 2 == 0;
    $: doubled = randomNumber * randomNumber;

    $: {
        console.log(randomNumber);
    }
</script>

<button on:click={generateRandomNumber}>Random</button>
<br />
number: {randomNumber}
<br />
Even: {isEven}
<br />
Doubled: {doubled}

// react/src/examples/Reactivity.jsx
import { useState, useEffect } from "react";

export default function Reactivity() {
    const [randomNumber, setRandomNumber] = useState("");

    function generateRandomNumber() {
        setRandomNumber(Math.round(Math.random() * 100));
    }

    const isEven = randomNumber % 2 === 0;
    const doubled = randomNumber * randomNumber;

    useEffect(() => {
        console.log(randomNumber);
    }, [randomNumber]);

    return (
        <div>
            <button onClick={generateRandomNumber}>Random</button>
            <br />
            number: {randomNumber}
            <br />
            Even: {isEven.toString()}
            <br />
            Doubled: {doubled}
        </div>
    );
}
