// svelte-4/src/examples/Slot.svelte
<div class="container">
    <div class="header">
        <slot name="header" />
    </div>

    <div class="body">
        <slot name="body" />
    </div>
</div>

<style>
    .container {
        display: flex;
        gap: 10px;
    }

    .header {
        color: blue;
    }

    .body {
        color: red;
    }
</style>

// react/src/examples/Slot.jsx
export default function Slot({ header, body }) {
    const styles = {
        container: {
            display: "flex",
            gap: "10px",
        },
        header: {
            color: "blue",
        },
        body: {
            color: "red",
        },
    };

    return (
        <div style={styles.container}>
            <div style={styles.header}>{header}</div>
            <div style={styles.body}>{body}</div>
        </div>
    );
}
