// svelte-4/src/examples/Slots.svelte
<script>
    import Slot from "./Slot.svelte";
</script>

<Slot>
    <span slot="header">AAAAA</span>
    <div slot="body">aaaaa</div>
</Slot>

<Slot>
    <span slot="header">BBBBB</span>
    <div slot="body">bbbbb</div>
</Slot>

<Slot>
    <span slot="header">CCCCC</span>
    <div slot="body">ccccc</div>
</Slot>

// react/src/examples/Slots.jsx
import Slot from "./Slot";

export default function Slots() {
    return (
        <>
            <Slot header={<span>AAAAA</span>} body={<div>aaaaa</div>} />
            <Slot header={<span>BBBBB</span>} body={<div>bbbbb</div>} />
            <Slot header={<span>CCCCC</span>} body={<div>ccccc</div>} />
        </>
    );
}
