// react/src/examples/ComponentsCounter.jsx
import { useState } from "react";

import ComponentsCounterButtonIncrease from "./ComponentsCounterButtonIncrease";
import ComponentsCounterButtonDecrease from "./ComponentsCounterButtonDecrease";

export default function ComponentsCounter() {
    const [counter, setCounter] = useState(0);

    return (
        <div>
            <ComponentsCounterButtonDecrease counter={counter} setCounter={setCounter} /> {counter} <ComponentsCounterButtonIncrease counter={counter} setCounter={setCounter} />
        </div>
    );
}

// svelte-4/src/examples/ComponentsCounter.svelte
<script>
    import ComponentsCounterButtonIncrease from "./ComponentsCounterButtonIncrease.svelte";
    import ComponentsCounterButtonDecrease from "./ComponentsCounterButtonDecrease.svelte";

    let counter = 0;
</script>

<ComponentsCounterButtonDecrease bind:counter />

{counter}

<ComponentsCounterButtonIncrease bind:counter />
