// react/src/examples/StoresCounter.jsx
import { useCounter } from "./StoresCounterContext";

import StoresCounterButtonIncrease from "./StoresCounterButtonIncrease";
import StoresCounterButtonDecrease from "./StoresCounterButtonDecrease";

export default function StoresCounter() {
    const { counter } = useCounter();

    return (
        <div>
            <StoresCounterButtonDecrease /> {counter} <StoresCounterButtonIncrease />
        </div>
    );
}

// svelte-4/src/examples/StoresCounter.svelte
<script>
    import StoresCounterButtonIncrease from "./StoresCounterButtonIncrease.svelte";
    import StoresCounterButtonDecrease from "./StoresCounterButtonDecrease.svelte";

    import { counter } from "./stores";
</script>

<StoresCounterButtonDecrease />

{$counter}

<StoresCounterButtonIncrease />
