// svelte-4/src/examples/Binding.svelte
<script>
    let value = "";

    let firstInputElement;
</script>

Two-way: <input type="text" bind:value bind:this={firstInputElement} /><br />
One-way: <input type="text" {value} /><br />
Two-way: <input type="text" bind:value />
<br />
<br />

<button
    on:click={() => {
        firstInputElement.select();
    }}
>
    Focus first input
</button>

// angular/src/app/examples/binding.component.ts
import { Component, signal, ViewChild, ElementRef } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-binding',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div>
      Two-way: <input type="text" [(ngModel)]="value" #firstInput /><br />
      One-way: <input type="text" [value]="value()" /><br />
      Two-way: <input type="text" [(ngModel)]="value" />
      <br />
      <br />

      <button (click)="focusFirstInput()">Focus first input</button>
    </div>
  `,
})
export class BindingComponent {
  value = signal('');

  @ViewChild('firstInput') firstInputElement!: ElementRef<HTMLInputElement>;

  focusFirstInput() {
    this.firstInputElement.nativeElement.select();
  }
}
