// svelte-4/src/examples/Binding.svelte
<script>
    let value = "";

    let firstInputElement;
</script>

Two-way: <input type="text" bind:value bind:this={firstInputElement} /><br />
One-way: <input type="text" {value} /><br />
Two-way: <input type="text" bind:value />
<br />
<br />

<button
    on:click={() => {
        firstInputElement.select();
    }}
>
    Focus first input
</button>

// vue/src/examples/Binding.vue
<template>
    <div>
        Two-way: <input type="text" v-model="value" ref="firstInputElement" /><br />
        One-way: <input type="text" :value="value" /><br />
        Two-way: <input type="text" v-model="value" />
        <br />
        <br />

        <button @click="firstInputElement.select()">Focus first input</button>
    </div>
</template>

<script setup>
import { ref } from "vue";

const value = ref("");
const firstInputElement = ref(null);
</script>
