// svelte-5/src/examples/ComponentsCounter.svelte
<script>
    import ComponentsCounterButtonIncrease from "./ComponentsCounterButtonIncrease.svelte";
    import ComponentsCounterButtonDecrease from "./ComponentsCounterButtonDecrease.svelte";

    let counter = $state(0);
</script>

<ComponentsCounterButtonDecrease bind:counter />

{counter}

<ComponentsCounterButtonIncrease bind:counter />

// vue/src/examples/ComponentsCounter.vue
<template>
    <div>
        <ComponentsCounterButtonDecrease v-model:counter="counter" />
        {{ counter }}
        <ComponentsCounterButtonIncrease v-model:counter="counter" />
    </div>
</template>

<script setup>
import { ref } from "vue";
import ComponentsCounterButtonDecrease from "./ComponentsCounterButtonDecrease.vue";
import ComponentsCounterButtonIncrease from "./ComponentsCounterButtonIncrease.vue";

const counter = ref(0);
</script>
