// react/src/examples/Loops.jsx
import { useState } from "react";

export default function Loops() {
    const [todos] = useState([
        { id: 1, text: "foo" },
        { id: 2, text: "bar" },
        { id: 3, text: "baz" },
    ]);

    return (
        <>
            {todos.map((todo, i) => (
                <div key={todo.id} className="todo">
                    <span className="text">
                        {i} {todo.text}
                    </span>
                </div>
            ))}
        </>
    );
}

// vue/src/examples/Loops.vue
<template>
    <div v-for="(todo, i) in todos" :key="todo.id" class="todo">
        <span class="text">{{ i }} {{ todo.text }}</span>
    </div>
</template>

<script setup>
import { ref } from "vue";

const todos = ref([
    { id: 1, text: "foo" },
    { id: 2, text: "bar" },
    { id: 3, text: "baz" },
]);
</script>
