// svelte-5/src/examples/Reactivity.svelte
<script>
    let randomNumber = $state("");

    function generateRandomNumber() {
        randomNumber = Math.round(Math.random() * 100);
    }

    let isEven = $derived(randomNumber % 2 == 0);
    let doubled = $derived(randomNumber * randomNumber);
</script>

<button onclick={generateRandomNumber}>Random</button>

number: {randomNumber}
<br />
<br />
Even: {isEven}
<br />
<br />
Doubled: {doubled}

// vue/src/examples/Reactivity.vue
<template>
    <button @click="generateRandomNumber">Random</button>
    <br />
    number: {{ randomNumber }}
    <br />
    Even: {{ isEven }}
    <br />
    Doubled: {{ doubled }}
</template>

<script setup>
import { ref, computed } from "vue";

const randomNumber = ref("");

function generateRandomNumber() {
    randomNumber.value = Math.round(Math.random() * 100);
}

const isEven = computed(() => randomNumber.value % 2 === 0);
const doubled = computed(() => randomNumber.value * randomNumber.value);
</script>
