// svelte-5/src/examples/Slots.svelte
<script>
    import Slot from "./Slot.svelte";
</script>

<div class="container">
    <Slot>
        {#snippet header()}
            <span>AAAAA</span>
        {/snippet}
        {#snippet body()}
            <div>aaaaa</div>
        {/snippet}
    </Slot>

    <Slot>
        {#snippet header()}
            <span>BBBBB</span>
        {/snippet}
        {#snippet body()}
            <div>bbbbb</div>
        {/snippet}
    </Slot>

    <Slot>
        {#snippet header()}
            <span>CCCCC</span>
        {/snippet}
        {#snippet body()}
            <div>ccccc</div>
        {/snippet}
    </Slot>
</div>

// vue/src/examples/Slots.vue
<template>
    <div class="container">
        <Slot>
            <template #header>
                <span>AAAAA</span>
            </template>
            <template #body>
                <div>aaaaa</div>
            </template>
        </Slot>

        <Slot>
            <template #header>
                <span>BBBBB</span>
            </template>
            <template #body>
                <div>bbbbb</div>
            </template>
        </Slot>

        <Slot>
            <template #header>
                <span>CCCCC</span>
            </template>
            <template #body>
                <div>ccccc</div>
            </template>
        </Slot>
    </div>
</template>

<script setup>
import Slot from "./Slot.vue";
</script>
