// svelte-4/src/examples/StoresCounter.svelte
<script>
    import StoresCounterButtonIncrease from "./StoresCounterButtonIncrease.svelte";
    import StoresCounterButtonDecrease from "./StoresCounterButtonDecrease.svelte";

    import { counter } from "./stores";
</script>

<StoresCounterButtonDecrease />

{$counter}

<StoresCounterButtonIncrease />

// vue/src/examples/StoresCounter.vue
<template>
    <div>
        <StoresCounterButtonDecrease />
        {{ counter }}
        <StoresCounterButtonIncrease />
    </div>
</template>

<script setup>
import { counter } from "./stores";
import StoresCounterButtonIncrease from "./StoresCounterButtonIncrease.vue";
import StoresCounterButtonDecrease from "./StoresCounterButtonDecrease.vue";
</script>
